### ISSUE TITLE
Issue: Update `coastsat_package`  Dependency to Handle Request Size Limits Gracefully

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#202]
#### Current Behavior
When using the `coastsat_package` package, if 10 or more requests exceed the download request size limit set by Google Earth Engine, all ongoing downloads halt abruptly.

#### Expected Behavior
The package should be updated to ensure that:
- Each request that exceeds the request size limit is printed/logged for review.
- Any remaining downloads continue 

#### Goal
The primary goal is to maximize data acquisition. The system should be robust enough to handle request size limits without interrupting the entire download process, ensuring that the maximum amount of data is downloaded even if some data points are missed due to size constraints.

#### Steps to Reproduce
1. Initiate multiple downloads using the `coastsat_package` package where the expected request size exceeds the limit set by Google Earth Engine.
2. Observe the behavior when multiple requests go over the size limit.

_It's essential to address this issue to improve the reliability and efficiency of data collection processes using the `coastsat_package` package._

## Related Issues 
https://github.com/2320sharon/coastsat_package/issues/5

### Tasks

- [x] update the coastsat_package dependency in the pyproject.toml

- [x] Test the updated version with the config information in sample_data.zip
[sample_data.zip](https://github.com/Doodleverse/CoastSeg/files/13284523/sample_data.zip)

**Comment by 2320sharon** [comment]
I've tested coastsat, coastsat_package, and coastseg with the inputs included in this issue. Both coastseg and  coastsat_package encountered the issue with the request limit being exceeded. When I examined the downloaded imagery I noticed some of the images were just noise as you can see in the screenshot. However when I examined the coastsat downloads I noticed that those dates were not included in the downloaded imagery. This leads me to believe there was an update to coastsat that handles prevented these bad images from being downloaded.

 
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/0906e0f5-0bf6-444f-a361-15f340e39030)


- [ ] I will need to investigate coastsat's code further and update coastsat_package's code accordingly.

**Comment by 2320sharon** [comment]
Closed in coastseg 1.1.15
