### ISSUE TITLE
Bug: ee Authenticate method is deprecated and blocking requests

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#211]
Tools like Geemap have run into the same issue as we have that Google is deprecating how their 0Auth method works. Apartently a project id now needs to be manually entered into the `ee.Initialize(project='my-project-id')`  as discovered by [giswqs](https://github.com/giswqs).

## Tasks
- [x] Understand the deprecation
- [x] Figure out how to fix it
- [x] Figure out a long term fix
- [x] Update the instructions to authenticate if necessary
- [x] Update the  authentication gif if necessary
- [x] implement this fix in all notebooks

## Related Issues
https://github.com/gee-community/geemap/issues/1870

## Resources
- https://support.google.com/accounts/answer/12379384
- https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

## Screenshots
![Screenshot 2024-01-10 085656](https://github.com/Doodleverse/CoastSeg/assets/61564689/1afba281-6643-4087-b66e-a776e2765c6c)

![image (8)](https://github.com/Doodleverse/CoastSeg/assets/61564689/c519888f-0fa0-4ec0-babf-b3957d0bd63c)

**Comment by 2320sharon** [comment]
The paragraph below explains how the new method of authentication works. 


## New Authentication Method with GEE
Source: https://developers.google.com/earth-engine/guides/auth

Python and Command Line
Prior to using the Earth Engine Python client library, you need to authenticate (verify your identity) and use the resultant credentials to initialize the Python client. The authentication flows use [Cloud Projects](https://developers.google.com/earth-engine/cloud/earthengine_cloud_project_setup) to authenticate, and they're used for unpaid (free, noncommercial) use as well as paid use. To authenticate and initialize, run


    ee.Authenticate()
    ee.Initialize(project='my-project')
This will first select the best authentication mode for your environment, and prompt you to confirm access for your scripts. If credentials already exist, they are automatically reused - run ee.Authenticate(force=True) to create new credentials.

The initialization step verifies that valid credentials exist, either created from ee.Authenticate() or pre-existing as Google default credentials. It then initializes the Python client library with methods that the backend server supports. You will need to provide a project that you own, or have [permissions](https://developers.google.com/earth-engine/cloud/roles_permissions) to use, that also has the Earth Engine [API enabled](https://developers.google.com/earth-engine/cloud/earthengine_cloud_project_setup#enable-the-earth-engine-api). This project will be used for running all Earth Engine operations.

On the command line, the equivalent call is earthengine authenticate. Provide a project for further calls using earthengine set_project {my-project}. Command line invocations will initialize automatically as needed.

**Comment by Dasize** [comment]
Thanks ! works fine

**Comment by 2320sharon** [comment]
CoastSeg only runs on the user's local computer, which means we can use `auth_mode='localhost'`. The authmode='localhost' can only be run on local computers and is actually much simpler to use than the old default method that was previously used to authenticate.

## Solution
```
import ee
from google.auth import exceptions as google_auth_exceptions

ee.Authenticate(auth_mode='localhost')
ee.Initialize()
```

**Comment by 2320sharon** [comment]
Updated the instructions in the coastsat notebook

![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/6368fdb4-2b34-4221-9baa-f8b6cc6ecdc9)

**Comment by 2320sharon** [comment]
- Created a new gif you can see it here https://github.com/Doodleverse/CoastSeg/blob/main/docs/gifs/tutorial_for_authenticate_new.gif
and it has been embeded directly into the `SDS_coastsat_classifier.ipynb` in v1.1.25.
- I also updated the instructions in `SDS_coastsat_classifier.ipynb` in v1.1.25.
- I created a new function  in `common.py` called `initialize_gee` that initializes and authenticates with GEE. A call to this function has replaced the old code block in `SDS_coastsat_classifier.ipynb` that  authenticates with GEE
![tutorial_for_authenticate_new](https://github.com/Doodleverse/CoastSeg/assets/61564689/b2c6482e-de06-475d-b2b0-6807b615d5bb)
