### ISSUE TITLE
Documentation: Create new Diagrams for CoastSeg

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#215]
## Purpose
We need to create new diagrams to represent what CoastSeg does.

## Tasks
**Create figures of the following**
- [ ] a high level view of how CoastSeg works
- [ ] a high level view of how shoreline extraction works
- [ ] an example extracted shoreline
- [ ] updated screenshots of the CoastSeg UI
- [ ] How CoastSeg tide correction process works & how its different than CoastSat tide correction process

**Comment by 2320sharon** [comment]
## High Level Diagram of how Coastseg Works

[coastseg_figure1.drawio.zip](https://github.com/Doodleverse/CoastSeg/files/14128498/coastseg_figure1.drawio.zip)
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/7f3b7e48-9f93-4616-a5ab-b0c7326ca290)
[coastseg_figure1_svg.drawio.zip](https://github.com/Doodleverse/CoastSeg/files/14128520/coastseg_figure1_svg.drawio.zip)

### Figure Description
Figure 1.		A flowchart of the CoastSeg workflows.
A schematic of the workflows of the CoastSeg application. First, a user selects a Region of Interest (ROI) on the map and specifies the necessary satellites and dates for data acquisition. With the acquired data the user selects either the Coastsat or Zoo workflow by loading the appropriate notebook.
(a) The CoastSat workflow creates a session to store all the extracted shoreline data. The user then fine-tunes the settings to optimize the extraction of the most accurate shorelines from the multispectral data. The user selects the most accurate shorelines to be used to construct a tidally corrected time series of shoreline changes along the designated transects.
(b) The Zoo workflow the process similarly begins with the creation of a session. This session is designed to encapsulate both the shorelines extracted from the multispectral data and the model parameters. Following the session creation the user specifies a model to extract shorelines from the multispectral data. The model's output undergoes an automated filtering process, ensuring only the most accurate shorelines are extracted. These shorelines are then utilized to construct a tidally corrected time series of shoreline changes along the designated transects.

**Comment by 2320sharon** [comment]
![CoastSeg_tide_correction_paper drawio](https://github.com/Doodleverse/CoastSeg/assets/61564689/d24d31af-970a-4fce-928f-67edd17a5d2f)
![coastsat_tide_correction_paper drawio](https://github.com/Doodleverse/CoastSeg/assets/61564689/680e9b16-34d8-495d-bc41-7d72ad22d3c7)

**Comment by 2320sharon** [comment]
- [ ] Put updated gifs on the readme
