### ISSUE TITLE
Script: Convert the shoreline position along the transect to geojson

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#220]
Write a script that can take the cross shore distance reported in the tidally corrected file and turn it into a geojson point.

## Tasks

- [x] Read the transects from the file
- [x] Read the cross shoreline distance along the transect from the file
- [x] Figure out where the shoreline point is relative to the transect. Is it relative to the origin of the transect?
- [x] Convert this point to a lat lon point. Check if coastseg does something similar
- [x] Give this file to the TCA group

## Related Issues
#206

**Comment by 2320sharon** [comment]
Closed in v1.2.0
