### ISSUE TITLE
CoastSat notebook: Add a line to specify a project ID for GEE

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#225]
Add a line into the notebook that tells the user to enter the project ID in case the google auth method doesn't work.

```
import ee
# enter your project ID 
ee.Initialize(project='sample_id')
```

## Tasks
- [ ] Add the line to `SDS_coastsat_classifier.ipynb`
- [ ] Make this line commented out
- [ ] Add instructions on when to run this line 
- [ ] Show the user where they can find this info
- [ ] Reference how geemap does this for reference

**Comment by 2320sharon** [comment]
Google brought back the old notebook way of authenticating later after deprecating it.

According to https://developers.google.com/earth-engine/guides/auth
The default auth mode will be :
```
notebook if running in other non-Colab Jupyter notebooks
localhost if a web browser is detected and no gcloud binary is installed
```
This means in our notebooks the default method will be 'notebook' and we should only tell the user to specify the project id if the selected project does not have earth engine enabled.

The full changelog of changes to earth engine is here https://developers.google.com/earth-engine/changelog#python_api_v01383

- [ ] Update the minimum version of earth-engine required in the pyproject.toml to be greater than 0.1.388
- [ ] Allow the user to pass auth_mode = 'notebook'
- [ ] Run auth with notebook by default and localhost as a backup method
- [ ] Tell the user when they need to enter their project id and provide default code
- [ ] Link the user to a tutorial on how to get the user id
- [ ] Bring back the old gif with notebook

**Comment by 2320sharon** [comment]
These changes have been merged into main and will be added in the next official release.

![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/0898abb3-ab93-4675-9379-d406404c7466)
