### ISSUE TITLE
Feature Request: Filter Shorelines within a Polygon

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/CoastSeg#232]
# Shoreline Filtering

![image (16)](https://github.com/Doodleverse/CoastSeg/assets/61564689/928ab4d0-ee88-465a-a976-4f4854d871b5)

We want to implement improve outlier remove for our extracted shorelines. Currently shorelines a filtered by removing any detected shoreline points that lie outside of the reference shoreline buffer. This new technique would have the user draw a polygon that would define where extracted shorelines could be extracted then extract all the shorelines and then filter the extracted shorelines to keep only the shorelines that exist within the polygon.

If this technique were implemented first the points outside reference shoreline buffer would be filtered out, then more points would be filtered out if they were outside the polygon.

### Key Elements of this solution
- Applied after shoreline extraction from images
- Uses the shorelines gdf that are saved as LineStrings
- Maintains the order of points when applying filter to each linestring segment.

### Tasks

- [x] Verify this technique works on complex shorelines
- [x] Verify this technique works on  back barrier shorelines
- [x] Verify the code to preserve extracted shorelines attributes

Credit @mlundine for the figure and code.
```
import numpy as np
import os
import geopandas as gpd
import shapely
from shapely import geometry

def arr_to_LineString(coords):
    """
    Makes a line feature from a list of xy tuples
    inputs: coords
    outputs: line
    """
    points = [None]*len(coords)
    i=0
    for xy in coords:
        points[i] = shapely.geometry.Point(xy)
        i=i+1
    line = shapely.geometry.LineString(points)
    return line

def LineString_to_arr(line):
    """
    Makes an array from linestring
    inputs: line
    outputs: array of xy tuples
    """
    listarray = []
    for pp in line.coords:
        listarray.append(pp)
    nparray = np.array(listarray)
    return nparray



def ref_poly_filter(reference_polygon, model_shorelines):
    """python
    filters extracted shorelines that are not contained within a reference region/polygon
    saves output with '_ref_poly_filter' appended to original filename in same directory
    inputs:
    reference_region_path (str): path to reference region geojson
    model_shorelines (str): path to extracted shorelines
    outputs:
    save_path (str): path to the output file
    """

    ##Loading stuff in
    save_path = os.path.splitext(model_shorelines)[0]+'_ref_poly_filter.geojson'
    model_gdf = gpd.read_file(model_shorelines)
    ref_poly_gdf = gpd.read_file(reference_polygon)

    ##First need to get rid of lines that are completely outside of the ref polygon
    ref_polygon = ref_poly_gdf.geometry
    buffer_vals = [None]*len(model_gdf)
    for i in range(len(model_gdf)):
        line_entry = model_gdf.iloc[i]
        line = line_entry.geometry
        bool_val = ref_polygon.intersects(line).values[0]
        buffer_vals[i] = bool_val
    model_gdf['buffer_vals'] = buffer_vals
    model_gdf_filter = model_gdf[model_gdf['buffer_vals']]

    ##Now get rid of points that lie outside ref polygon but preserve the rest of the shoreline
    new_lines = [None]*len(model_gdf_filter)
    for i in range(len(model_gdf_filter)):
        line_entry = model_gdf_filter.iloc[i]
        line = line_entry.geometry
        line_arr = LineString_to_arr(line)
        bool_vals = [None]*len(line_arr)
        j = 0
        for point in line_arr:
            point = geometry.Point(point)
            bool_val = ref_polygon.contains(point)[0]
            bool_vals[j] = bool_val
            j=j+1
        new_line_arr = line_arr[bool_vals]
        new_line_LineString = arr_to_LineString(new_line_arr)
        new_lines[i] = new_line_LineString

    ##Assign the new geometries, save the output
    model_gdf_filter['geometry'] = new_lines
    model_gdf_filter.to_file(save_path)

    return save_path

```

**Comment by 2320sharon** [comment]
If this technique works we will need to make sure these shorelines are used to compute the shoreline transect intersections.

**Comment by 2320sharon** [comment]
## Test Case One Gilgo Beach 
### Original Extracted Shorelines
![2023-11-29-15-33-54_L8](https://github.com/Doodleverse/CoastSeg/assets/61564689/0074da61-07af-49a0-8cff-70ce5f75c658)

![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/6933a601-ed72-4b94-aa75-880d4e6d5253)

### Filtered Shorelines
- Red: reference shoreline polygon I drew
- Green: Filtered Shorelines
- After filtering there are still 4 remaining shorelines
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/b4d47182-3b7a-4fd1-b8d4-cbf65a650f2f)

### Source Code and Extracted Shoreline Zip
[NY_back_barrier1.zip](https://github.com/Doodleverse/CoastSeg/files/14463212/NY_back_barrier1.zip)

[keep_shorelines_in_polygon.zip](https://github.com/Doodleverse/CoastSeg/files/14463218/keep_shorelines_in_polygon.zip)

**Comment by 2320sharon** [comment]
![image (17)](https://github.com/Doodleverse/CoastSeg/assets/61564689/e164f54c-0f45-44ce-91c9-90fed19ad14a)
This is what the shoreline points looked like when they were plotted on the map

**Comment by mlundine** [comment]
This method btw preserves the attributes I had made that edit in the slack message to do so.
Just had to reassign geometry to the existing filtered gdf instead of making a new gdf.

**Comment by 2320sharon** [comment]
Here's the latest on the shoreline filtering with the polygon.

- Named the polygon the user draws `shoreline_extraction_area`
- The polygon is optional and can be draw by the user if they select to draw the shoreline extraction area under draw controls
- The filtering it working great it filters both the geodataframe and the dictionary for all the extracted shorelines
- Catherine is going to beta test this feature
![Untitled (2)](https://github.com/Doodleverse/CoastSeg/assets/61564689/8b64272d-15f6-4b20-bd8f-fae10d7bf801)

**Comment by 2320sharon** [comment]
![2023-12-19-16-01-08_L9](https://github.com/Doodleverse/CoastSeg/assets/61564689/68898ace-2c0a-4990-b1cc-41d734c1a901)

After Catherine verifies the feature works I'll need to update the coastsat_package's extract_shoreline function to plot the only the shoreline detected in the `shoreline extraction area` because if I don't update those code the detection images will not reflect the filtered shorelines.

I'll update this after Catherine verifies it works for her 2 test sites

**Comment by 2320sharon** [comment]
During our meeting today I realized I never had tested the new shorelines extraction area feature with multiple ROI. Good news is it works. The thing is is that if users want to use this feature for multiple ROI they will need to draw a shoreline extraction area for each ROI they have selected not just one. This makes logical sense to me, but what do you think?
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/8bb71a3e-5051-49d8-9992-97040af26aa9)
![Screenshot 2024-03-07 113721](https://github.com/Doodleverse/CoastSeg/assets/61564689/87a61faf-ac7a-4c57-91bb-db915cd3bba0)
![image](https://github.com/Doodleverse/CoastSeg/assets/61564689/c0461043-143a-4139-ad7f-575d4ca3ed4b)

**Comment by 2320sharon** [comment]
- [ ] Make a wiki tutorial on how to use this feature
- [ ] Plot the shoreline extraction figures with the shoreline extraction area
